### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by krt16s** [benjaminaigner/aiproute#2]
Is this app GPLv2+ (GPLv2 "and later")? If not, you might have a problem because android-support libraries are Apache2 licensed and thus incompatible with plain GPLv2

**Comment by benjaminaigner** [comment]
Hi,

sry. for the confusion.
I would like to publish it anyway, and I don't care much about which OSS license I'm using.

So I will use GPLv2 and later, I've to update the source files.

**Comment by benjaminaigner** [comment]
Closed with 8429004ed3fa6f5f794cba66bc27975060f43110
License information added, GPLv3

**Comment by krt16s** [comment]
Thanks for the quick response. You might want to update the main LICENSE file, too :)
