### ISSUE TITLE
Potential Compatibility Issue

### ISSUE THREAD

**Issue by tsmrafee** [benjaminaigner/aiproute#9]
Hi, 
I notice in class systems/byteswap/aiproute/SettingsActivity.java you have overridden function `isValidFragment()`, which is added to the class android.preference.PreferenceActivity in API version = 19. (See this [link](https://developer.android.com/sdk/api_diff/19/changes/android.preference.PreferenceActivity)).

Class SettingsActivity directly extends `android.preference.PreferenceActivity`.  If you put some important operation into this function, the program may not execute normally in API<19.

**Comment by benjaminaigner** [comment]
@tsmrafee 

THX for reporting.

What do you suggest, should I change the API level to >=19?

**Comment by tsmrafee** [comment]
Yes, you should change the minSdkVersion to 19.

**Comment by benjaminaigner** [comment]
THX for the info,
I changed the minSDK level.
